// <auto-generated />
using System;
using System.Collections.Generic;
using Messenger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Messenger.Migrations.Dialogs
{
    [DbContext(typeof(DialogsContext))]
    [Migration("20200714172330_ChangeDialogs")]
    partial class ChangeDialogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Dialog")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Messenger.Data.Entities.Dialog", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<List<Guid>>("Participants")
                        .HasColumnType("uuid[]");

                    b.HasKey("Uuid");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("Messenger.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DialogUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DialogUuid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Messenger.Data.Entities.Read", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UuidParticipant")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Read");
                });

            modelBuilder.Entity("Messenger.Data.Entities.Message", b =>
                {
                    b.HasOne("Messenger.Data.Entities.Dialog", "Dialog")
                        .WithMany("Messages")
                        .HasForeignKey("DialogUuid");
                });

            modelBuilder.Entity("Messenger.Data.Entities.Read", b =>
                {
                    b.HasOne("Messenger.Data.Entities.Message", null)
                        .WithMany("Reads")
                        .HasForeignKey("MessageId");
                });
#pragma warning restore 612, 618
        }
    }
}
